data:
  name: pl
  path: ./data/crossdocked_v1.1_rmsd1.0_processed
  split: ./data/split_by_name.pt
  mode: full
  include_dummy_atoms: False
  version: ref_prior_aromatic
  prior_mode: ref_prior
  transform:
    add_ord_feat: False
    ligand_atom_mode: basic
    ligand_bond_mode: fc
    max_num_arms: 10
    random_rot: False

model:
  model_mean_type: C0  # ['noise', 'C0']

  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000

  v_mode: categorical
  v_net_type: mlp
  loss_pos_type: mse  # ['mse', 'kl']
  sample_time_method: symmetric  # ['importance', 'symmetric']

  bond_diffusion: True
  bond_net_type: lin
  num_bond_classes: 5
  prior_types: False
  h_node_in_bond_net: True

  add_prior_node: False

  time_emb_dim: 0
  time_emb_mode: simple
  center_pos_mode: protein

  node_indicator: True
  model_type: uni_o2_bond
  num_blocks: 1
  num_layers: 6
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 # !
  act_fn: relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False

train:
  seed: 2021
  loss_weights:
    pos: 1.0
    v: 100.0
    bond: 100.0

  batch_size: 4
  num_workers: 4
  n_acc_batch: 1
  max_iters: 500000
  val_freq: 2000
  pos_noise_std: 0.1
  prior_noise_std: 0.5
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  optimizer:
    type: adam
    lr: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-6
